export const BLOG_CONFIG = {
  identity: {
    name: 'San Diego Buy Guy',
    siteUrl: 'https://sandiegobuyguy.com',
    siteHost: 'sandiegobuyguy.com',
    agent: {
      name: 'Kristian Peter',
      title: 'broker',
      titleCap: 'Broker',
      license: 'CA DRE #01308663',
      since: 2002,
    },
    areas: [
      'La Jolla',
      'Del Mar',
      'Coronado',
      'Rancho Santa Fe',
      'Carlsbad',
      'Encinitas',
      'Downtown San Diego',
      'Pacific Beach',
      'Point Loma',
      'North Park',
      'Carmel Valley',
    ],
    voice: { name: 'BRI', homeCtaPath: '/', valuationPath: '/sell' },
    backlink: {
      url: 'https://bizrnr.com',
      deepLink: 'https://bizrnr.com/ai-voice-receptionist',
    },
  },

  paths: {
    blogDir: 'src/content/blog',
    assetDir: 'public/assets/blog',
    heroDir: 'public/assets/blog/generated',
    brandLogo: 'public/assets/brand/wordmark.png',
    watermarkLogo: 'public/assets/brand/logo-full.png',
  },

  gsc: {
    property: 'sc-domain:sandiegobuyguy.com',
    sitemap: 'https://sandiegobuyguy.com/sitemap-index.xml',
  },

  indexNow: {
    key: 'f28d3065d7645b6a0580bdac1d6d9c09',
  },

  text: {
    provider: 'openrouter',
    url: 'https://openrouter.ai/api/v1/chat/completions',
    model: 'deepseek/deepseek-v4-flash',
    maxTokens: 4000,
    temperature: 0.7,
  },

  image: {
    model: 'openai/gpt-image-2',
    size: '1536x1024' as const,
    quality: 'high' as const,
    format: 'webp' as const,
    credit: 'Generated by AI (OpenAI gpt-image-2)',
    promptMarket: 'San Diego luxury residential real estate',
    promptStyle:
      'Style: hyper-realistic Southern California luxury real-estate photography, natural coastal light, believable architecture, refined landscaping, premium editorial composition, grounded in the blog title.',
    promptCamera:
      'Camera: full-frame DSLR realism, 24-35mm architectural lens, natural depth, realistic shadows, true-to-life materials, high dynamic range, crisp but not over-sharpened.',
    watermark: {
      width: 210,
      opacity: 0.84,
      margin: 32,
    },
    og: {
      width: 1200,
      height: 630,
      colors: {
        bg: '#06080B',
        bg2: '#0b0f16',
        gold: '#C9A24B',
        gold2: '#E6CB84',
        text: '#F4EFE4',
        dim: 'rgba(240,235,224,0.56)',
      },
      titleFont: 'Georgia, "Times New Roman", serif',
      uiFont: '"Helvetica Neue", Arial, sans-serif',
    },
  },

  rss: {
    title: 'San Diego Buy Guy Insights',
    description:
      'San Diego real estate guides, neighborhood notes, luxury market insights, and AI-enabled lead capture strategy from San Diego Buy Guy.',
    path: '/blog/feed.xml',
    limit: 20,
  },

  logPrefix: '[sdbg-blog]',
} as const;

export function brandPersona(): string {
  const { identity } = BLOG_CONFIG;
  const a = identity.agent;
  return [
    `You are the content writer for ${identity.name} (${identity.siteHost}), the brand of ${a.name},`,
    `a licensed California real estate ${a.titleCap} since ${a.since} (${a.license}). Always call ${a.name.split(' ')[0]} a "${a.title}",`,
    `never a "Realtor" unless you are quoting a search phrase. The brand serves luxury buyers and sellers across ${identity.areas.join(', ')}.`,
    `"${identity.voice.name}" is the brand's 24/7 AI voice concierge powered by BizRnR and Business Runner.`,
  ].join(' ');
}
