import { configureBlogEngine } from '../src/config.js';
import type { BlogEngineConfig, BlogEngineHooks, BlogEngineRuntime, GeneratedBlogPost } from '../src/types.js';

export function testConfig(overrides: Partial<BlogEngineConfig> = {}): BlogEngineConfig {
  return {
    identity: {
      name: 'Acme Plumbing',
      siteUrl: 'https://acme-plumbing.example',
      siteHost: 'acme-plumbing.example',
      agent: { name: 'Alex Acme', title: 'master plumber', titleCap: 'Master Plumber', license: 'LIC-123' },
      areas: ['Springfield'],
      voice: { name: 'AVA', homeCtaPath: '/' },
      backlink: { url: 'https://bizrnr.com', deepLink: 'https://bizrnr.com/automation' },
    },
    paths: {
      blogDir: 'src/content/blog',
      assetDir: 'public/assets/blog',
      heroDir: 'public/assets/blog/generated',
      brandLogo: 'public/logo.png',
      watermarkLogo: 'public/logo.png',
    },
    gsc: { property: 'sc-domain:acme-plumbing.example', sitemap: 'https://acme-plumbing.example/sitemap.xml' },
    indexNow: { key: 'test-key' },
    text: {
      provider: 'openrouter',
      url: 'https://openrouter.ai/api/v1/chat/completions',
      model: 'test/model',
      maxTokens: 4000,
      temperature: 0.7,
    },
    image: {
      model: 'openai/gpt-image-2',
      size: '1536x1024',
      quality: 'high',
      format: 'webp',
      credit: 'Generated by AI',
      promptMarket: 'Springfield plumbing',
      promptStyle: 'editorial photography',
      promptCamera: 'full-frame DSLR',
      watermark: { width: 210, opacity: 0.84, margin: 32 },
      og: {
        width: 1200,
        height: 630,
        colors: { bg: '#05060a', bg2: '#0b1015', gold: '#facc15', gold2: '#eab308', text: '#f4f4f0', dim: '#a8b3b7' },
        titleFont: 'Georgia, serif',
        uiFont: 'Arial, sans-serif',
      },
    },
    rss: { title: 'Acme Insights', description: 'Plumbing answers', path: '/blog/feed.xml', limit: 20 },
    ...overrides,
  };
}

export function configureTestEngine(
  overrides: Partial<BlogEngineConfig> = {},
  hooks?: BlogEngineHooks,
): BlogEngineRuntime {
  const runtime: BlogEngineRuntime = {
    config: testConfig(overrides),
    topics: {
      allowedCategories: ['Guides', 'Local'],
      crossPromoEvery: 4,
      gradients: ['g1', 'g2'],
      heroPhotos: [{ url: 'https://images.example/fallback.jpg', alt: 'Fallback hero' }],
      internalLinks: ['/', '/blog', '/services/drain-cleaning'],
      editorial: [{ keyword: 'winter pipe care', category: 'Guides', angle: 'prevention' }],
      crossPromo: [{ keyword: 'AVA voice intake', angle: 'lead capture' }],
    },
    brandPersona: () => 'You are the blog writer for Acme Plumbing.',
    hooks,
  };
  configureBlogEngine(runtime);
  return runtime;
}

export function validPost(): GeneratedBlogPost {
  const quote = Array(90).fill('word').join(' ');
  return {
    title: 'How Much Does Drain Cleaning Cost in Springfield?',
    slug: 'drain-cleaning-cost-springfield',
    description:
      'See what drives drain cleaning prices in Springfield, when to call a pro, and how to avoid repeat clogs with simple maintenance.',
    category: 'Guides',
    answer: Array(40).fill('answer').join(' '),
    readMins: 6,
    tags: ['drain cleaning', 'pricing', 'springfield'],
    heroImageAlt: 'plumber clearing a kitchen drain under a stainless sink',
    faqs: [
      { q: 'How often should drains be cleaned?', a: 'Most homes benefit from annual cleaning. High-use kitchens may need more.' },
      { q: 'Can I use chemical cleaners?', a: 'They can damage older pipes. Mechanical cleaning is safer for most systems.' },
      { q: 'When is a clog an emergency?', a: 'Sewage backup or multiple blocked fixtures needs a same-day professional visit.' },
    ],
    body: [
      'Drain cleaning in Springfield is priced by access difficulty and clog severity, not by fixture count alone.',
      '',
      '## What drives the price of drain cleaning?',
      Array(60).fill('cost').join(' '),
      '',
      '## How do pros actually clear a drain?',
      Array(60).fill('method').join(' '),
      '',
      `> ${quote} as of July 2026.`,
      '',
      '## Can you prevent clogs entirely?',
      Array(60).fill('prevent').join(' ') + ' Learn more in our [drain guide](/services/drain-cleaning).',
      '',
      '## What should Springfield homeowners do next?',
      Array(60).fill('next').join(' '),
      '',
      'Ready for help? [speak with AVA](/) any time.',
      Array(120).fill('filler').join(' '),
    ].join('\n'),
  };
}
