/**
 * The provider seams, backward compatibility, and domain agnosticism.
 *
 * These run entirely offline: every external dependency (model, image model, Search Console) is
 * supplied through the hooks the seams exist to expose, which is itself the point — if the engine
 * can be driven with no network, no API key and no vendor, then it is genuinely portable.
 */
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { configureBlogEngine } from '../src/config.js';
import { getGscQueries, pingGscSitemap } from '../src/gsc.js';
import { generateBlogRun } from '../src/publisher.js';
import { configureTestEngine, testConfig, validPost } from './helpers.js';
import type { BlogEngineConfig, BlogEngineRuntime } from '../src/types.js';

const postJson = () => JSON.stringify(validPost());

/** Capture console output for a dry run, which prints the file it would have written. */
async function captureRun(): Promise<string> {
  const lines: string[] = [];
  const real = console.log;
  console.log = (...a: unknown[]) => void lines.push(a.map(String).join(' '));
  try {
    await generateBlogRun(process.cwd(), { count: 1, dryRun: true, skipPing: true });
  } catch (err) {
    lines.push(`ERR ${(err as Error).message}`);
  } finally {
    console.log = real;
  }
  return lines.join('\n');
}

/* ------------------------------------------------------------- seam 1: GSC --- */

test('fetchGscQueries hook supplies topics without any OAuth credentials', async () => {
  let seen: { property: string; days: number } | null = null;
  configureTestEngine({}, {
    fetchGscQueries: async ({ property, days }) => {
      seen = { property, days };
      return [
        { query: 'singleword', impressions: 900 },           // filtered: one word
        { query: 'acme plumbing reviews', impressions: 800 }, // filtered: brand term
        { query: 'drain smells like sewage', impressions: 50 },
        { query: 'water heater making noise', impressions: 5 },
      ];
    },
  });

  const { token, queries } = await getGscQueries();
  assert.equal(token, null, 'no OAuth token exists on the hook path');
  assert.deepEqual(seen, { property: 'sc-domain:acme-plumbing.example', days: 28 });
  assert.deepEqual(
    queries.map((q) => q.query),
    ['drain smells like sewage', 'water heater making noise'],
    'engine filters + impression ordering still apply to hook-supplied rows',
  );
});

test('submitSitemap hook replaces the OAuth sitemap ping', async () => {
  let submitted = '';
  configureTestEngine({}, { submitSitemap: async ({ sitemap }) => void (submitted = sitemap) });
  await pingGscSitemap(null); // no token — the hook owns its own auth
  assert.equal(submitted, 'https://acme-plumbing.example/sitemap.xml');
});

/* -------------------------------------------------------- seam 2: markdown --- */

test('renderMarkdown hook owns the frontmatter shape', async () => {
  configureTestEngine({}, {
    generateText: async () => postJson(),
    generateHeroImage: async () => null,
    renderMarkdown: ({ post, cover, dateISO }) =>
      `---\nCUSTOM: true\ntitle: "${post.title}"\ndate: "${dateISO}"\nogImage: "${cover.ogImage}"\n---\n\n${post.body}\n`,
  });

  const out = await captureRun();
  assert.match(out, /CUSTOM: true/, 'custom shape emitted');
  assert.doesNotMatch(out, /gradient:/, 'engine default frontmatter not emitted');
  assert.doesNotMatch(out, /feature: false/);
});

/* --------------------------------------------------------- seam 3: OG card --- */

test('image.og.enabled=false makes the hero double as the OG image', async () => {
  const config = testConfig();
  const withOgOff: BlogEngineConfig = { ...config, image: { ...config.image, og: { ...config.image.og, enabled: false } } };
  configureTestEngine(withOgOff, { generateText: async () => postJson(), generateHeroImage: async () => null });

  const out = await captureRun();
  assert.match(out, /ogImage: "https:\/\/images\.example\/fallback\.jpg"/, 'ogImage is the hero, not a generated card');
  assert.doesNotMatch(out, /ogImage: "\/assets\/blog\//, 'no separate OG card asset was produced');
});

/* --------------------------------------------------- backward compatibility --- */

test('with none of the new seams, behaviour is unchanged', async () => {
  configureTestEngine({}, { generateText: async () => postJson(), generateHeroImage: async () => null });

  const legacy = await getGscQueries();
  assert.deepEqual(legacy, { token: null, queries: [] }, 'no hook + no OAuth env degrades quietly');
  await pingGscSitemap(null); // must be a silent no-op, not a throw

  const out = await captureRun();
  assert.match(out, /gradient:/, 'engine frontmatter still emitted by default');
  assert.match(out, /feature: false/);
  assert.match(out, /ogImage: "\/assets\/blog\//, 'OG card still generated by default');
});

/* ------------------------------------------------------- domain agnosticism --- */

test('a minimal identity in an unrelated industry runs clean', async () => {
  // No voice agent, no partner backlink, no licence, no service areas, own categories.
  const base = testConfig();
  const config: BlogEngineConfig = {
    ...base,
    identity: {
      name: 'Fen & Field Bakery',
      siteUrl: 'https://fenandfield.example',
      siteHost: 'fenandfield.example',
      agent: { name: 'Fen & Field Bakery' },
      ctaPath: '/visit',
    },
  };

  let prompt = '';
  const runtime: BlogEngineRuntime = {
    config,
    topics: {
      allowedCategories: ['Baking Guides', 'Ingredients'],
      crossPromoEvery: 2, // would fire on this ordinal if cross-promo were possible at all
      gradients: ['g1'],
      heroPhotos: [{ url: '/loaf.jpg', alt: 'A sourdough loaf' }],
      internalLinks: ['/', '/blog'],
      editorial: [{ keyword: 'how to store sourdough', category: 'Baking Guides', angle: 'crust and crumb' }],
      crossPromo: [],
    },
    brandPersona: () => 'You write for a neighbourhood bakery.',
    hooks: {
      generateText: async ({ messages }) => {
        prompt = messages.map((m) => m.content).join('\n');
        const post = validPost();
        return JSON.stringify({
          ...post,
          category: 'Baking Guides',
          // The shared fixture links to a plumbing service page; this site allows only / and /blog.
          body: post.body.replace('/services/drain-cleaning', '/blog'),
        });
      },
      generateHeroImage: async () => null,
      fetchGscQueries: async () => [{ query: 'sourdough storage tips', impressions: 40 }],
    },
  };
  configureBlogEngine(runtime);

  const out = await captureRun();
  assert.doesNotMatch(out, /ERR /, `run must complete for a minimal identity: ${out.slice(0, 200)}`);

  for (const term of ['real estate', 'realtor', 'broker', 'bizrnr', 'receptionist', 'la jolla', 'san diego', 'never misses a lead']) {
    assert.ok(!prompt.toLowerCase().includes(term), `industry/vendor term leaked into the prompt: "${term}"`);
  }
  assert.match(prompt, /\(\/visit\)/, 'generic CTA points at identity.ctaPath');
  assert.doesNotMatch(prompt, /by voice/, 'no voice-agent CTA without a configured voice');
  assert.doesNotMatch(out, /Buying|Selling|Neighborhoods/, 'no real-estate category fallback');
});

test('cross-promo is skipped when no backlink is configured', async () => {
  const base = testConfig();
  const config: BlogEngineConfig = { ...base, identity: { ...base.identity, backlink: undefined } };
  const runtime: BlogEngineRuntime = {
    config,
    topics: {
      allowedCategories: ['Guides'],
      crossPromoEvery: 1, // every post would be cross-promo if it were possible
      gradients: ['g1'],
      heroPhotos: [{ url: '/x.jpg', alt: 'x' }],
      internalLinks: ['/', '/blog', '/services/drain-cleaning'],
      editorial: [{ keyword: 'winter pipe care', category: 'Guides', angle: 'prevention' }],
      crossPromo: [],
    },
    brandPersona: () => 'persona',
    hooks: { generateText: async () => postJson(), generateHeroImage: async () => null },
  };
  configureBlogEngine(runtime);

  const out = await captureRun();
  assert.doesNotMatch(out, /ERR /, 'no backlink must not break the run');
  assert.match(out, /\[editorial\]/, 'falls back to an editorial topic instead of cross-promo');
});
