import { createSupabaseStore } from '../../src/index.js';
import type { BlogEngineConfig, BlogEngineRuntime, BlogEngineTopics, ServiceSite } from '../../src/index.js';

/**
 * A multi-site blog service.
 *
 * Every site is one entry. Adding a site is adding an object — no repository, no workflow, no
 * secret, no deploy. The store makes publishing an upsert, so nothing here touches git or CI.
 */

interface SiteBrief {
  id: string;
  brand: string;
  domain: string;
  categories: string[];
  internalLinks: string[];
  ownerPages: string[];
  editorial: Array<{ keyword: string; category: string; angle: string }>;
  persona: string;
  days?: number[];
}

/** Everything a site needs that the engine cannot infer, and nothing it can. */
const BRIEFS: SiteBrief[] = [
  {
    id: 'acme-plumbing',
    brand: 'Acme Plumbing',
    domain: 'https://acmeplumbing.com',
    categories: ['Guides', 'Maintenance'],
    internalLinks: ['/', '/blog', '/services/drain-cleaning', '/contact'],
    ownerPages: ['/services/drain-cleaning'],
    editorial: [
      { keyword: 'winter pipe care', category: 'Maintenance', angle: 'prevention checklist' },
      { keyword: 'drain cleaning cost', category: 'Guides', angle: 'what drives the price' },
    ],
    persona: 'You write for Acme Plumbing, a family plumbing company. Practical, plain, never alarmist.',
    days: [1, 4], // Mondays and Thursdays (UTC)
  },
  {
    id: 'summit-roofing',
    brand: 'Summit Roofing',
    domain: 'https://summitroofing.example',
    categories: ['Guides', 'Storm Damage'],
    internalLinks: ['/', '/blog', '/services/roof-replacement', '/contact'],
    ownerPages: ['/services/roof-replacement'],
    editorial: [{ keyword: 'hail damage inspection', category: 'Storm Damage', angle: 'what to check first' }],
    persona: 'You write for Summit Roofing. Calm, specific, and honest about what needs a professional.',
  },
];

function runtimeFor(brief: SiteBrief): BlogEngineRuntime {
  const host = new URL(brief.domain).host;

  const config: BlogEngineConfig = {
    identity: {
      name: brief.brand,
      siteUrl: brief.domain,
      siteHost: host,
      agent: { name: brief.brand },
      author: { name: brief.brand, url: '/about', id: `${brief.domain}/#person` },
      locale: 'en-US',
      ctaPath: '/contact',
    },
    paths: {
      blogBasePath: '/blog',
      // Only meaningful for a filesystem store; the Supabase store ignores them.
      blogDir: 'content/blog',
      assetDir: 'public/assets/blog',
      heroDir: 'public/assets/blog/generated',
      brandLogo: 'public/logo.png',
      watermarkLogo: 'public/logo.png',
    },
    gsc: { property: `sc-domain:${host}`, sitemap: `${brief.domain}/sitemap.xml` },
    indexNow: { key: process.env.INDEXNOW_KEY || '' },
    text: {
      provider: 'openrouter',
      url: 'https://openrouter.ai/api/v1/chat/completions',
      model: process.env.BLOG_TEXT_MODEL || 'deepseek/deepseek-v4-flash',
      maxTokens: 4000,
      temperature: 0.7,
    },
    image: {
      model: 'openai/gpt-image-2',
      size: '1536x1024',
      quality: 'high',
      format: 'webp',
      variants: [1024, 640],
      credit: 'Generated by AI',
      promptMarket: brief.brand,
      promptStyle: 'Hyper-realistic editorial photography, natural light, believable environment.',
      promptCamera: 'Full-frame DSLR realism, 24-35mm lens, natural depth, true-to-life materials.',
      watermark: { width: 210, opacity: 0.84, margin: 32 },
      og: {
        width: 1200,
        height: 630,
        colors: { bg: '#05060a', bg2: '#0b1015', gold: '#facc15', gold2: '#eab308', text: '#f4f4f0', dim: '#a8b3b7' },
        titleFont: 'Georgia, serif',
        uiFont: 'Arial, sans-serif',
      },
    },
    rss: { title: `${brief.brand} Insights`, description: `Answer-first guides from ${brief.brand}.`, path: '/blog/feed.xml', limit: 20 },
    content: { maxPostsPerWeek: 2 },
  };

  const topics: BlogEngineTopics = {
    allowedCategories: brief.categories,
    crossPromoEvery: 4,
    gradients: ['g1', 'g2', 'g3'],
    heroPhotos: [{ url: '/assets/fallback.jpg', alt: `${brief.brand} team at work` }],
    internalLinks: brief.internalLinks,
    ownerPages: brief.ownerPages,
    editorial: brief.editorial,
    crossPromo: [],
    preferVerificationIntent: true,
  };

  return {
    config,
    topics,
    brandPersona: () => brief.persona,
    // One line is the whole difference between "a post is a commit" and "a post is a row".
    hooks: { store: createSupabaseStore({ siteId: brief.id, author: brief.brand }) },
  };
}

export const sites: ServiceSite[] = BRIEFS.map((brief) => ({
  id: brief.id,
  runtime: () => runtimeFor(brief),
  ...(brief.days ? { days: brief.days } : {}),
}));
